branch-defaults:
  master:
    environment: gep-data-service
environment-defaults:
  gep-data-service:
    branch: null
    repository: null
global:
  application_name: gep
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on 64bit Amazon Linux/4.7.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application