version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

      # Redis
      - image: redis:5.0

      # Database for the tests
      - image: circleci/postgres:11
        environment:
          POSTGRES_PASSWORD: gep-data-service-test
          POSTGRES_USER: gep-data-service-test
          POSTGRES_DB: gep-data-service-test

    working_directory: ~/repo

    environment:
      # Needed to load the correct config
      NODE_ENV: circle
      EB_DEPLOY_ENV: gep-data-service
      PRODUCTION_BRANCH: master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Set up the test db
          command: node node_modules/.bin/knex migrate:latest

      - run:
          name: Seed db
          command: node node_modules/.bin/knex seed:run

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run tests
          command: node node_modules/mocha/bin/mocha test/test--index.js
