knex:
  client: "pg"
  connection:
    host: "localhost"
    database: "gep-data-service-test"
    user: "gep-data-service-test"
    password: "gep-data-service-test"
    port: 5432
redisConnection:
  host: 127.0.0.1
  port: 6379
